on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test:
    name: "Linux"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK 21
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
          - jdkconf: JDK 21
            jdkver: "21"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick xvfb
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver }}
      - name: Run
        run: java -version
      - name: Run tests
        run: |
          mkdir -p workspace
          Xvfb :1 &
          XVFB_PID=$!
          sleep 10
          export BINARY_FOLDER="${JAVA_HOME}"
          export DISPLAY=:1
          export OTOOL_JDK_VERSION=${{ matrix.jdkver }}
          export OTOOL_jresdk=sdk
          export OTOOL_OS_NAME=ubuntu
          export OTOOL_OS_VERSION=2404
          export TTL=60 # set TTL not to do manual run
          export WORKSPACE="${PWD}/workspace"
          ./wrapper/run.sh
          kill $XVFB_PID
      - name: Check results
        run: |
          cat workspace/results/results.txt
          grep '^rhqa.failed=0$' workspace/results/results.properties
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -czf results.tar.gz -C workspace results
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: guitests-jdk${{ matrix.jdkver}}
          path: "results.tar.gz"
